
export const employeeData = [
  { name: 'Anowar Hossain Saiful', department: 'CNG', jobRole: 'Engineer', salary: 15000 },
  { name: 'Shibu chakrabarti', department: 'CNG', jobRole: '', salary: 36000 },
  { name: 'Monjurul Islam', department: 'CNG', jobRole: 'Engineer', salary: 17000 },
  { name: 'Md. Sizar', department: 'CNG', jobRole: 'Helper', salary: 11000 },
  { name: 'Amjad Hossain Faruk', department: 'CNG', jobRole: 'Cash Man', salary: 5000 },
  { name: 'Siddik Miya', department: 'CNG', jobRole: 'Cash Man', salary: 5000 },
  { name: 'Nozrul Islam', department: 'CNG', jobRole: 'Cash Man', salary: 5000 },
  { name: 'Jony', department: 'CNG', jobRole: 'Nozel Man', salary: 3200 },
  { name: 'Mishu', department: 'CNG', jobRole: 'Nozel Man', salary: 3200 },
  { name: 'Bahadur', department: 'CNG', jobRole: 'Nozel Man', salary: 3200 },
  { name: 'Josim', department: 'CNG', jobRole: 'Nozel Man', salary: 3200 },
  { name: 'Ponik', department: 'CNG', jobRole: 'Nozel Man', salary: 3200 },
  { name: 'Amam', department: 'CNG', jobRole: 'Nozel Man', salary: 3200 },
  { name: 'Nazmul', department: 'CNG', jobRole: 'Nozel Man', salary: 2800 },
  { name: 'Toiyub', department: 'CNG', jobRole: 'Nozel Man', salary: 2800 },
  { name: 'Saiful', department: 'CNG', jobRole: 'Nozel Man', salary: 2800 },
  { name: 'AZMIR', department: 'CNG', jobRole: 'Nozel Man', salary: 3200 },
  { name: 'Hanif', department: 'CNG', jobRole: 'Nozel Man', salary: 3000 },
  { name: 'shahabuddin', department: 'CNG', jobRole: 'Gard', salary: 5000 },
  { name: 'Sohid', department: 'CNG', jobRole: 'Gard', salary: 5500 },
  { name: 'Shahab uddin', department: 'CNG', jobRole: 'Driver', salary: 15000 },
  { name: 'Abdul Khalek', department: 'Filling', jobRole: 'Manager', salary: 26500 },
  { name: 'Nishan', department: 'Filling', jobRole: 'C.O', salary: 32000 },
  { name: 'Ripon Das', department: 'Filling', jobRole: 'Cash Man', salary: 8000 },
  { name: 'Ruhul Amin', department: 'Filling', jobRole: 'Cash Man', salary: 8000 },
  { name: 'Mostofa mia', department: 'Filling', jobRole: 'Miter Man', salary: 3200 },
  { name: 'Shahjahan', department: 'Filling', jobRole: 'Miter Man', salary: 3200 },
  { name: 'Alamin', department: 'Filling', jobRole: 'Piyon', salary: 4700 },
  { name: 'Iqbal Hossain Sumon', department: 'Feed', jobRole: 'Manager', salary: 36200 },
  { name: 'Rashedul Alom', department: 'Feed', jobRole: 'Account', salary: 12000 },
  { name: 'Amzad hossain', department: 'Feed', jobRole: 'Account', salary: 11000 },
  { name: 'Shahadat Hossain Liton', department: 'Feed', jobRole: 'M R Officer', salary: 12000 },
  { name: 'Akbor', department: 'Feed', jobRole: 'Mastori', salary: 8000 },
  { name: 'Arafat', department: 'Feed', jobRole: 'Mastori', salary: 8000 },
  { name: 'Arif', department: 'Feed', jobRole: 'Mastori', salary: 8000 },
  { name: 'Baker', department: 'Feed', jobRole: 'Mastori', salary: 8000 },
  { name: 'Murad', department: 'Feed', jobRole: 'Mastori', salary: 8000 },
  { name: 'Nizam', department: 'Feed', jobRole: 'Mastori', salary: 8000 },
  { name: 'Arif', department: 'Tech', jobRole: 'Manager', salary: 35000 },
  { name: 'Saiful vai', department: 'Tech', jobRole: 'Marketing manager', salary: 10000 },
  { name: 'Noyon', department: 'Tech', jobRole: 'Mastori', salary: 17000 },
  { name: 'Foysal', department: 'Tech', jobRole: 'Cabal man', salary: 8000 },
  { name: 'Arman', department: 'Tech', jobRole: 'Cabal man', salary: 11000 },
  { name: 'Anaf', department: 'Tech', jobRole: 'Cabal man', salary: 10000 },
  { name: 'Lufa', department: 'Tech', jobRole: 'Account', salary: 8000 },
  { name: 'Sojib', department: 'Tech', jobRole: 'Cabal man', salary: 6000 },
  { name: 'Hridoy', department: 'Tech', jobRole: 'Cabal man', salary: 9000 },
  { name: 'Nurujjaman Vuttu', department: 'Bricks', jobRole: '', salary: 20000 },
  { name: 'Halim', department: 'Bricks', jobRole: '', salary: 10000 },
];
