'use client';
import { useState } from 'react';
import { useForm } from 'react-hook-form';
import { z } from 'zod';
import { zodResolver } from '@hookform/resolvers/zod';
import { Search, Loader2 } from 'lucide-react';

import { Input } from '@/components/ui/input';
import { Button } from '@/components/ui/button';
import {
  Form,
  FormControl,
  FormField,
  FormItem,
} from '@/components/ui/form';
import { naturalLanguageDataRetrieval, type NaturalLanguageDataRetrievalOutput } from '@/ai/flows/natural-language-data-retrieval';
import { useToast } from '@/hooks/use-toast';
import { Alert, AlertDescription, AlertTitle } from '../ui/alert';
import { Card, CardContent } from '../ui/card';

const formSchema = z.object({
  query: z.string().min(1, 'Please enter a query.'),
});

export function NlqInput() {
  const [isLoading, setIsLoading] = useState(false);
  const [aiResponse, setAiResponse] = useState<NaturalLanguageDataRetrievalOutput | null>(null);
  const { toast } = useToast();

  const form = useForm<z.infer<typeof formSchema>>({
    resolver: zodResolver(formSchema),
    defaultValues: {
      query: '',
    },
  });

  async function onSubmit(values: z.infer<typeof formSchema>) {
    setIsLoading(true);
    setAiResponse(null);
    try {
      const response = await naturalLanguageDataRetrieval({ query: values.query });
      setAiResponse(response);

      if (response.actions.length > 0) {
        toast({
            title: "Action Generated by AI",
            description: `The system will now: ${response.actions[0].type.replace('_', ' ')}`
        });
      }

      if (response.followups.length === 0) {
        form.reset();
      }

    } catch (error) {
      console.error(error);
      toast({
        variant: 'destructive',
        title: 'An error occurred',
        description: 'Failed to process your natural language query.',
      });
    } finally {
      setIsLoading(false);
    }
  }

  function handleFollowupOption(option: string) {
    const originalQuery = form.getValues('query');
    const newQuery = `${originalQuery} for ${option}`;
    form.setValue('query', newQuery);
    // Automatically submit the form with the clarified query
    onSubmit({ query: newQuery });
  }

  return (
    <div className="relative w-full max-w-lg">
      <Form {...form}>
        <form onSubmit={form.handleSubmit(onSubmit)} className="relative">
          <FormField
            control={form.control}
            name="query"
            render={({ field }) => (
              <FormItem>
                <FormControl>
                  <div className="relative">
                    <Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground" />
                    <Input
                      placeholder="Show sales today for fuel stations..."
                      className="w-full bg-muted pl-10"
                      {...field}
                      disabled={isLoading}
                    />
                    {isLoading && (
                        <Loader2 className="absolute right-3 top-1/2 h-4 w-4 -translate-y-1/2 animate-spin" />
                    )}
                  </div>
                </FormControl>
              </FormItem>
            )}
          />
        </form>
      </Form>
      {aiResponse?.followups && aiResponse.followups.length > 0 && (
        <Card className="absolute top-full z-20 mt-2 w-full shadow-lg">
          <CardContent className="p-4">
          {aiResponse.followups.map((followup, index) => (
            <Alert key={index} variant="default" className="border-primary">
              <AlertTitle className="font-semibold">{followup.question}</AlertTitle>
              {followup.options && followup.options.length > 0 ? (
                <AlertDescription>
                  <div className="mt-2 flex flex-wrap gap-2">
                    {followup.options.map(option => (
                      <Button key={option} variant="outline" size="sm" onClick={() => handleFollowupOption(option)}>
                        {option}
                      </Button>
                    ))}
                  </div>
                </AlertDescription>
              ) : null}
            </Alert>
          ))}
          </CardContent>
        </Card>
      )}
    </div>
  );
}
